# Generated by Django 4.0.3 on 2022-04-17 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_question_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceA', models.CharField(max_length=5000)),
                ('choiceB', models.CharField(max_length=5000)),
                ('choiceC', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=5000),
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.question'),
        ),
    ]
