# Generated by Django 4.0.3 on 2022-04-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_choice_rename_users_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('Alexis', models.CharField(max_length=10)),
                ('Pearl', models.CharField(max_length=10)),
                ('KimShego', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiceA',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiceB',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiceC',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=1000),
        ),
    ]
