# Generated by Django 4.0.3 on 2022-04-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_persona_alter_choice_choicea_alter_choice_choiceb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='name',
            new_name='Persona_Names',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiceA',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiceB',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiceC',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=100),
        ),
    ]
