# Generated by Django 4.0.3 on 2022-04-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_name_persona_persona_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='Persona_Names',
        ),
        migrations.AlterField(
            model_name='persona',
            name='Alexis',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='persona',
            name='KimShego',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='persona',
            name='Pearl',
            field=models.TextField(max_length=500),
        ),
    ]
