# Generated by Django 4.0.3 on 2022-04-18 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_persona_persona_names_alter_persona_alexis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='Alexis',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='KimShego',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='Pearl',
        ),
        migrations.AddField(
            model_name='persona',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='AssesmentResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scores', models.IntegerField(max_length=100)),
                ('TextDescription', models.TextField(max_length=100)),
                ('PersonaType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.persona')),
            ],
        ),
    ]
