# Generated by Django 4.0.3 on 2022-04-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_persona_alexis_remove_persona_kimshego_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assesmentresults',
            name='TextDescription',
        ),
        migrations.AddField(
            model_name='persona',
            name='TextDescription',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='name',
            field=models.CharField(default='Enter Persona Name', max_length=20),
        ),
    ]
