# Generated by Django 4.0.3 on 2022-04-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_assesmentresults_textdescription_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssesmentResults',
            new_name='AssesmentResult',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choiceA',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choiceB',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choiceC',
            new_name='C',
        ),
        migrations.AlterField(
            model_name='persona',
            name='TextDescription',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
