# Generated by Django 4.0.3 on 2022-05-09 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_assesmentresults_assesmentresult_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssesmentResult',
            new_name='AssessmentResult',
        ),
    ]
